// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_crptHsY8Pt-vBi2SZ5H8qc7LMRg3-t4',
    appId: '1:188836983499:web:0c107d752758d954e1a14e',
    messagingSenderId: '188836983499',
    projectId: 'course-planner-dec45',
    authDomain: 'course-planner-dec45.firebaseapp.com',
    storageBucket: 'course-planner-dec45.firebasestorage.app',
    measurementId: 'G-4QE2FGXJNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSDu7bXL5lufEzg509gHpRqowgW2C5oM',
    appId: '1:188836983499:android:db4473e56d7f20d5e1a14e',
    messagingSenderId: '188836983499',
    projectId: 'course-planner-dec45',
    storageBucket: 'course-planner-dec45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihYKGg6sR-U4tFNWCj6l4Y9_5VdLLmy4',
    appId: '1:188836983499:ios:c1df13181b294e1be1a14e',
    messagingSenderId: '188836983499',
    projectId: 'course-planner-dec45',
    storageBucket: 'course-planner-dec45.firebasestorage.app',
    iosBundleId: 'com.darylldancc.iskotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihYKGg6sR-U4tFNWCj6l4Y9_5VdLLmy4',
    appId: '1:188836983499:ios:591627307a2a1d41e1a14e',
    messagingSenderId: '188836983499',
    projectId: 'course-planner-dec45',
    storageBucket: 'course-planner-dec45.firebasestorage.app',
    iosBundleId: 'com.example.coursePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_crptHsY8Pt-vBi2SZ5H8qc7LMRg3-t4',
    appId: '1:188836983499:web:f2e6676ea1d525a3e1a14e',
    messagingSenderId: '188836983499',
    projectId: 'course-planner-dec45',
    authDomain: 'course-planner-dec45.firebaseapp.com',
    storageBucket: 'course-planner-dec45.firebasestorage.app',
    measurementId: 'G-HLYWDXZQ6S',
  );

}